server:
  port: "${PORT:8080}"
  origin: "${ORIGIN:*}"
spring:
  application:
    name: "challenge-fullstack-game"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/bettingGame"
  rabbitmq:
    addresses: "amqp://guest:guest@localhost:5672"
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rsocket
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
